package org.jellyfin.mobile.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * The two colour schemes, in full.
 *
 * Both are generated by `tools/palette.py` — run it and paste, rather than editing a value here by
 * hand. Every number below is a tone of one of four hues, and the script is also what checks that
 * each foreground clears 4.5:1 on the surface it is drawn against. A hand-tweaked value silently
 * breaks both of those properties.
 *
 * Why a whole scheme rather than the handful of roles this app names directly: Material's components
 * read roles we never mention. A `TopAppBar` is `surfaceContainer`, a `Card` is `surfaceContainerLow`,
 * a `Checkbox`'s border is `onSurfaceVariant`, a `Snackbar` is `inverseSurface`. Overriding five
 * roles and inheriting the rest meant every one of those came from Material's baseline lavender —
 * unnoticeable against a near-black background, and obviously not ours in a light one.
 *
 * The four hues:
 *
 * - **primary**, the brand purple (`#9B59D0`);
 * - **secondary**, the brand blue (`#00A4DC`) — the two ends of Jellyfin's gradient;
 * - **tertiary**, the green already used for a watched badge, so the third accent is one the app
 *   was already spending;
 * - **error**, a red matched to Material's baseline by hue.
 *
 * Tones follow Material's assignment (light `primary` is tone 40, dark is a light tone, containers
 * are 90 and 30) with two deliberate departures, both noted where they apply.
 */

/**
 * Dark accents sit at tone 70, not the 80 Material specifies.
 *
 * Tone 80 is a pastel: correct, legible, and no longer recognisably Jellyfin. 70 is close to the
 * brand purple the app shipped with, and still clears 5.4:1 against its own `onPrimary` — whereas
 * the brand colour used unmodified reaches only 4.3:1 on `#101010`, which is why it could not simply
 * stay.
 *
 * The neutrals are the app's existing greys rather than generated ones: `#101010` and the ramp
 * around it were chosen for this app and there was no reason to move them.
 */
internal val DarkColors = darkColorScheme(
    primary = Color(0xFFBB87DE),
    onPrimary = Color(0xFF391650),
    primaryContainer = Color(0xFF552178),
    onPrimaryContainer = Color(0xFFE8D7F4),
    secondary = Color(0xFF66D6FF),
    onSecondary = Color(0xFF004B66),
    secondaryContainer = Color(0xFF007099),
    onSecondaryContainer = Color(0xFFCCF1FF),
    tertiary = Color(0xFF90D5A7),
    onTertiary = Color(0xFF1C4A2B),
    tertiaryContainer = Color(0xFF2A6F41),
    onTertiaryContainer = Color(0xFFDAF1E2),
    error = Color(0xFFEA867B),
    onError = Color(0xFF58160E),
    errorContainer = Color(0xFF842015),
    onErrorContainer = Color(0xFFF8D7D3),
    background = Color(0xFF101010),
    onBackground = Color(0xFFE6E6E6),
    surface = Color(0xFF101010),
    onSurface = Color(0xFFE6E6E6),
    surfaceVariant = Color(0xFF242424),
    onSurfaceVariant = Color(0xFFCDC9CF),
    surfaceTint = Color(0xFFBB87DE),
    surfaceDim = Color(0xFF0C0C0C),
    surfaceBright = Color(0xFF383838),
    surfaceContainerLowest = Color(0xFF0A0A0A),
    surfaceContainerLow = Color(0xFF161616),
    surfaceContainer = Color(0xFF1C1C1C),
    surfaceContainerHigh = Color(0xFF242424),
    surfaceContainerHighest = Color(0xFF2E2E2E),
    outline = Color(0xFF9A939F),
    outlineVariant = Color(0xFF4D4851),
    inverseSurface = Color(0xFFE6E6E6),
    inverseOnSurface = Color(0xFF333333),
    inversePrimary = Color(0xFF722CA0),
    scrim = Color(0xFF000000),
)

/**
 * The light scheme's blue and green sit at tone 30 rather than 40.
 *
 * Both are far more saturated than the purple, and HSL lightness overstates how dark a saturated
 * hue looks: tone 40 of either lands at about 3.4:1 on white, under what a label needs. One step
 * down puts them at 5.6:1 and 6.1:1. The purple stays at 40, where Material puts it.
 *
 * The surfaces carry the faintest purple tint rather than being pure grey, which is what keeps a
 * light Jellyfin from looking like an unthemed white app.
 */
internal val LightColors = lightColorScheme(
    primary = Color(0xFF722CA0),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE8D7F4),
    onPrimaryContainer = Color(0xFF1C0B28),
    secondary = Color(0xFF007099),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCF1FF),
    onSecondaryContainer = Color(0xFF002533),
    tertiary = Color(0xFF2A6F41),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDAF1E2),
    onTertiaryContainer = Color(0xFF0E2516),
    error = Color(0xFFAF2B1D),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF8D7D3),
    onErrorContainer = Color(0xFF2C0B07),
    background = Color(0xFFFAF8FB),
    onBackground = Color(0xFF1A1A1A),
    surface = Color(0xFFFAF8FB),
    onSurface = Color(0xFF1A1A1A),
    surfaceVariant = Color(0xFFE8E2EC),
    onSurfaceVariant = Color(0xFF4D4851),
    surfaceTint = Color(0xFF722CA0),
    surfaceDim = Color(0xFFDCD9E0),
    surfaceBright = Color(0xFFFAF8FB),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F2F7),
    surfaceContainer = Color(0xFFEFECF2),
    surfaceContainerHigh = Color(0xFFE9E6EC),
    surfaceContainerHighest = Color(0xFFE3E0E7),
    outline = Color(0xFF817887),
    outlineVariant = Color(0xFFCDC9CF),
    inverseSurface = Color(0xFF333333),
    inverseOnSurface = Color(0xFFF2F2F2),
    inversePrimary = Color(0xFFBB87DE),
    scrim = Color(0xFF000000),
)

/**
 * Card badge colours.
 *
 * Fixed rather than read off the colour scheme because they carry meaning of their own — blue is
 * "this much is left", green is "finished" — while `secondary` and `tertiary` are free to change
 * with the theme. [BadgeContent] is likewise not `onSecondary`. They sit on artwork rather than on
 * a surface, so they are the same in both schemes: a poster is as bright under a light theme as a
 * dark one, and a badge that followed the scheme would be the one thing on the card that did.
 */
internal val BadgeUnwatched = Color(0xFF00A4DC)
internal val BadgeWatched = Color(0xFF3EA55F)
internal val BadgeContent = Color.White
